server:
  port: 8089

spring:
  application:
    name: updg-ai

ai:
  dashscope:
    api-key: ${DASHSCOPE_API_KEY:}
    base-url: https://dashscope.aliyuncs.com

logging:
  config: classpath:logback-spring.xml
