server:
  port: 8095

spring:
  application:
    name: updg-quality
  datasource:
    url: jdbc:mysql://localhost:3306/updg_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:logback-spring.xml
