server:
  port: 8096

spring:
  application:
    name: updg-file
  datasource:
    url: jdbc:mysql://localhost:3306/updg_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: updg-files

logging:
  config: classpath:logback-spring.xml
