server:
  port: 8090

spring:
  application:
    name: updg-integration

integration:
  hr:
    base-url: ${HR_API_URL:}
  devops:
    base-url: ${DEVOPS_API_URL:}

logging:
  config: classpath:logback-spring.xml
